lipo -create ./a/FBReactNativeSpec/libFBReactNativeSpec.a ./b/FBReactNativeSpec/libFBReactNativeSpec.a -output ./c/libFBReactNativeSpec.a
lipo -create ./a/React-CoreModules/libReact-CoreModules.a ./b/React-CoreModules/libReact-CoreModules.a -output ./c/libReact-CoreModules.a
lipo -create ./a/React-RCTImage/libReact-RCTImage.a ./b/React-RCTImage/libReact-RCTImage.a -output ./c/libReact-RCTImage.a
lipo -create ./a/React-RCTSettings/libReact-RCTSettings.a ./b/React-RCTSettings/libReact-RCTSettings.a -output ./c/libReact-RCTSettings.a
lipo -create ./a/React-cxxreact/libReact-cxxreact.a ./b/React-cxxreact/libReact-cxxreact.a -output ./c/libReact-cxxreact.a
lipo -create ./a/React-jsinspector/libReact-jsinspector.a ./b/React-jsinspector/libReact-jsinspector.a -output ./c/libReact-jsinspector.a
lipo -create ./a/RCTTypeSafety/libRCTTypeSafety.a ./b/RCTTypeSafety/libRCTTypeSafety.a -output ./c/libRCTTypeSafety.a
lipo -create ./a/React-RCTAnimation/libReact-RCTAnimation.a ./b/React-RCTAnimation/libReact-RCTAnimation.a -output ./c/libReact-RCTAnimation.a
lipo -create ./a/React-RCTLinking/libReact-RCTLinking.a ./b/React-RCTLinking/libReact-RCTLinking.a -output ./c/libReact-RCTLinking.a
lipo -create ./a/React-RCTText/libReact-RCTText.a ./b/React-RCTText/libReact-RCTText.a -output ./c/libReact-RCTText.a
lipo -create ./a/React-jsi/libReact-jsi.a ./b/React-jsi/libReact-jsi.a -output ./c/libReact-jsi.a
lipo -create ./a/ReactCommon/libReactCommon.a ./b/ReactCommon/libReactCommon.a -output ./c/libReactCommon.a
lipo -create ./a/React-Core/libReact-Core.a ./b/React-Core/libReact-Core.a -output ./c/libReact-Core.a
lipo -create ./a/React-RCTBlob/libReact-RCTBlob.a ./b/React-RCTBlob/libReact-RCTBlob.a -output ./c/libReact-RCTBlob.a
lipo -create ./a/React-RCTNetwork/libReact-RCTNetwork.a ./b/React-RCTNetwork/libReact-RCTNetwork.a -output ./c/libReact-RCTNetwork.a
lipo -create ./a/React-RCTVibration/libReact-RCTVibration.a ./b/React-RCTVibration/libReact-RCTVibration.a -output ./c/libReact-RCTVibration.a
lipo -create ./a/React-jsiexecutor/libReact-jsiexecutor.a ./b/React-jsiexecutor/libReact-jsiexecutor.a -output ./c/libReact-jsiexecutor.a
lipo -create ./a/Yoga/libYoga.a ./b/Yoga/libYoga.a -output ./c/libYoga.a